config/routes.rb
Ooshew::Application.routes.draw do

  namespace :graph do
  get 'gephi_csv/create'
  end

  resources :articles
  root to: 'articles#index'

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessor :links

  belongs_to :author

  has_and_belongs_to_many :references,
    class_name: "Article",
    join_table: "article_references",
    foreign_key: "article_id",
    association_foreign_key: "referenced_article_id"

  validates :author, presence: true
  validates :url, presence: true, uniqueness: true

  def references_csv
    refs = self.references.map do |reference|
      "#{ reference.author.handle }, #{ reference.url }"
    end

    refs.join("\n")
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  require 'csv'
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: Rails.application.secrets["authentication"]["name"], password: Rails.application.secrets["authentication"]["password"]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    author = Author.find_or_create_by!({ handle: params[:article][:author] })
    author.articles << @article

    CSV.parse(params[:article][:references]).each do |reference|
      reference.map!(&:strip)

      author = Author.find_or_create_by!(handle: reference.first.downcase)
      url = reference.last

      reference = Article.find_or_create_by!({ url: url, author: author })

      @article.references << reference
    end

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    if params[:article][:references].present?
      @article.references = []

      CSV.parse(params[:article][:references]).each do |reference|
        reference.map!(&:strip)

        author = Author.find_or_create_by!(handle: reference.first.downcase)
        url = reference.last

        reference = Article.find_or_create_by!({ url: url, author: author })

        @article.references << reference
      end
    end

    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:article).permit(:url, :title, :author_id, :parent_id)
    end
end

app/views/articles/_form.html.slim
= simple_form_for(@article) do |f|
  = f.error_notification
  - author = @article.author.handle if @article.author.present?
  - references = @article.references_csv if @article.author.present?

  .form-inputs
    = f.input :title
    = f.input :url, autofocus: true
    = f.input :author, as: :string, label: "Author (twitter handle)", input_html: { value: author || "" }
    = f.input :references, as: :text, label: "References (author, url)", input_html: { value: references || "" }

  .form-actions
    = button_tag(type: 'submit', class: 'btn btn-primary') do
      = text_with_icon("#{btn_action_prefix} Article", action_icon_name)
    '
    = link_to text_with_icon('Back', 'chevron-left'), articles_path, class: 'btn btn-default'

app/views/articles/edit.html.slim
.page-header
  h1 Editing article

== render 'form'

app/views/articles/index.html.slim
div.page-header
  h1 Listing articles

  /- if can? :create, Article
  = link_to text_with_icon('New Article', 'plus'), new_article_path, class: 'btn btn-primary'
  = link_to text_with_icon('Export Graph', 'file'), graph_gephi_csv_create_path(format: :csv), class: 'btn btn-primary push-left'
  = link_to text_with_icon('Export Graph', 'file'), graph_gephi_csv_create_path(format: :csv), class: 'btn btn-primary push-left'

table.table.table-striped
  thead
    tr
      th ID
      th Url
      th Title
      th Author
      th References
      th Actions

  tbody
    - @articles.each do |article|
      tr
        /td= link_to_if can?(:show, article), article.id, article_path(article)
        td= link_to article.id, article_path(article)
        td= link_to article.url, article.url
        td= article.title
        td= article.author.identity
        td= article.references.count
        td
          = link_to text_with_icon('Edit', 'edit'), edit_article_path(article), class: 'btn btn-default btn-xs'
          '
          = link_to text_with_icon('Destroy', 'remove'), article_path(article), \
                    method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-default btn-xs btn-danger'

app/views/articles/new.html.slim
.page-header
  h1 Create article

== render 'form'

app/views/articles/show.html.slim
.page-header
  h1 Article

dl
  dt Url
  dd= @article.url
  dt Title
  dd= @article.title
  dt Author
  dd= @article.author_id
  dt Parent
  dd= @article.parent_id

/- if can?(:edit, @article)
= link_to text_with_icon('Edit', 'edit'), edit_article_path(@article), class: 'btn btn-default'
'
= link_to text_with_icon('Back', 'chevron-left'), articles_path, class: 'btn btn-default'

/- if can?(:destroy, @article)
'
= link_to text_with_icon('Destroy', 'remove'), article_path(@article), \
          method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'